version: "3.8"
services:
  web:
    image: nginx:1.17.10
    container_name: nginx
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ../www:/data
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
    links:
      - php-fpm
  php-fpm:
    container_name: php-fpm
    build: ./images/php-fpm
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ../www:/data # 必须将php和www的数据盘挂载到相同地方，否则$document_root指向不同的地方，而且连输出document_root都不行
      - ./php/etc:/usr/local/etc
      - ./php/log:/var/log/php
      # 不需要将9000端口到处去，因为links已经指向了9000端口
    links:
      - db
      - redis
  db:
    image: mysql:5.7
    container_name: mysql-msh
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=99@123
      # - MYSQL_DATABASE=laravel
      # - MYSQL_USER=laravel
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:5.0.9
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis:/usr/local/etc/redis
    ports:
      - 6379:6379
